is_official_build=true
symbol_level=0
disable_fieldtrial_testing_config=true
blink_enable_generated_code_formatting=false
blink_symbol_level=0
ffmpeg_branding="Chrome"
proprietary_codecs=true
fatal_linker_warnings=false
rtc_use_pipewire=true
is_clang=true
is_debug=false
use_kerberos=false
use_sysroot=false
sysroot="/"
use_vaapi=true
use_system_libffi=false
custom_toolchain="//build/toolchain/linux/unbundle:default"
host_toolchain="//build/toolchain/linux/unbundle:default"
treat_warnings_as_errors=false
fatal_linker_warnings=false
disable_fieldtrial_testing_config=true
blink_enable_generated_code_formatting=false
link_pulseaudio=true
use_custom_libcxx=true
enable_widevine=true
use_qt5=false
use_qt6=true
moc_qt6_path="/usr/lib/qt6/libexec"
enable_platform_hevc=true
enable_hevc_parser_and_hw_decoder=true
use_clang_modules=false
